### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NikolaZhechev** [bababoi-2/Deezer-Release-Radar#3]
Hello, the script hasn't been working for a while. Can I get an update?

**Comment by bertigert-2** [comment]
What isnt working? Im currently sitting on a dev build with unfinished features so the next general update might take a while. a hotfix is doable though

**Comment by NikolaZhechev** [comment]
> Какво не работи? В момента работя върху компилация за разработчици с незавършени функции, така че следващата обща актуализация може да отнеме известно време. актуална корекция обаче е изпълнима

The yellow light is constantly on, indicating that it is loading and it is not showing me any new releases.
![Екранна снимка 2024-12-10 145925](https://github.com/user-attachments/assets/8c5e2aed-e984-4d56-9c09-81ff80013241)

**Comment by bababoi-2** [comment]
Did you try hitting the reload button?
